-- TransactiDB Demo Script
SHOW TABLES
SELECT * WHERE ID = 1
BEGIN
UPDATE WHERE ID = 1 SET NAME = RAHUL
SELECT * WHERE ID = 1
ROLLBACK
SELECT * WHERE ID = 1
SELECT STUDENT.NAME, DEPARTMENT.DEPT_NAME FROM STUDENT JOIN DEPARTMENT ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID
